Sprint 1
skaamoogs/middle.messenger.praktikum.yandex pull request #1
Opened 2022-11-09 13:05 UTC by skaamoogs

2022-11-09 18:39 UTC, podlovchenko requested changes
Привет, локально проект не собирается
<img width="1186" alt="Снимок экрана 2022-11-09 в 21 33 22" src="https://user-images.githubusercontent.com/22602747/200913626-8b675608-eed5-486d-83f1-3c7f004f2727.png">

2022-11-09 18:39 UTC, podlovchenko commented on package.json
> +    "clean-dist": "rm -rf dist && mkdir dist",
rm -rf не будет работать на windows, можно использовать пакет https://www.npmjs.com/package/rimraf

2022-11-09 18:39 UTC, podlovchenko commented on package.json
> +    "@anikin/parcel-transformer-handlebars": "^1.0.9",
Лучше задавать фиксированные версии зависимостям. Если однажды решишь, удалить package-lock.json файл и попытаться повторно установить зависимости с помощью команды npm install, npm установит последние версии зависимостей, что может привести к ошибкам

2022-11-09 18:39 UTC, podlovchenko commented on package.json
> +    "express": "^4.18.2",
В devDependencies указывается то, что необходимо для сборки и разработки приложения, в dependencies то, что необходимо непосредственно для работу приложения (express)

2022-11-09 18:39 UTC, podlovchenko commented on server.js
> +const PORT = 3000;
Часто требуется возможность получить порт снаружи скрипта, не изменяя код, это можно сделать через переменное окружение:
process.env.PORT || PORT;
https://nodejs.org/dist/latest-v8.x/docs/api/process.html

2022-11-09 18:39 UTC, podlovchenko commented on server.js
> +  app.use(ROUTES[route], express.static(path.join(__dirname, "/dist")));
Можно указать просто app.use('*', ...
А на клиенте уже обрабатывать отдавать нужную страницу или страницу 404

2022-11-09 18:39 UTC, podlovchenko commented on src/components/form/_form.scss
> +      input {
Лучше использовать классы, а не теги
Статья на эту тему https://frontstuff.io/you-need-to-stop-targeting-tags-in-css

2022-11-09 18:39 UTC, podlovchenko commented on package.json
> +    "init": "npm run clean-dist && npm run copy-files",
Почему для запуска команд используется npm, а в проекте лежит yarn.lock, стоит выбрать что-то одно

2022-11-11 06:58 UTC, podlovchenko commented
Привет, при использовании yarn проект собирается и устанавливается, через npm ошибка при сборке, не исключаю, что проблема может быть у меня локально, но перед следующим спринтом перепроверь, пожалуйста, работу принимаю

2022-11-11 08:57 UTC, skaamoogs commented
Привет! Я с нуля себе клонировал, тоже вылезала ошибка при сборке через npm. Потом я удалил yarn.lock и заново установил все зависимости через npm, ещё раз попробовал клонировать и сборка через npm была без ошибок. Поэтому если есть проблема в проекте, не понятно как искать

2022-11-17 19:59 UTC, closed without merging